#!/bin/bash

export AWS_ACCESS_KEY_ID=<AWS-access-key>
export AWS_SECRET_ACCESS_KEY=<AWS-secret>
export BASE_DOMAIN=<Base-domain>
export AWS_REGION=<AWS-region>
export CLUSTER_NAME=<cluster-name>
export OCP_VERSION=4.12.9
export EC2_TYPE=m5.4xlarge
# export EC2_TYPE=m6a.2xlarge
export CONTROLPLANE_REPLICAS=1
export COMPUTE_REPLICAS=0
export PULL_SECRET_FILE=./pull-secret.txt
export OPENSHIFT_PULL_SECRET=$(<${PULL_SECRET_FILE})

